sudo: required
services:
  - docker
language: cpp

#env:

before_install:
  - docker pull fdiblen/ubuntu1604-test:latest
  - docker run -itd -v "${TRAVIS_BUILD_DIR}:/travis/workdir" --name ubuntu-build fdiblen/ubuntu1604-test:latest
  - docker pull fdiblen/sl7-test:latest
  - docker run -itd -v "${TRAVIS_BUILD_DIR}:/travis/workdir" --name sl-build fdiblen/sl7-test:latest
  - docker pull hspreeuw/running_sagecal:ubuntu1804
  - docker run -itd -v "${TRAVIS_BUILD_DIR}:/travis/workdir" --name ubuntu1804-build hspreeuw/running_sagecal:ubuntu1804
#  - docker pull base/archlinux
#  - docker run -itd -v "${TRAVIS_BUILD_DIR}:/travis/workdir" --name arch-build base/archlinux

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - docker exec -e BRANCH=$BRANCH -e IMAGE='ubuntu' ubuntu-build /bin/bash -c "/travis/workdir/build-tests/compile_sagecal.sh"
  - docker exec -e BRANCH=$BRANCH -e IMAGE='sl7' sl-build /bin/bash -c "/travis/workdir/build-tests/compile_sagecal.sh"
  - docker exec -e BRANCH=$BRANCH -e IMAGE='ubuntu1804' ubuntu1804-build /bin/bash -c "/travis/workdir/build-tests/compile_sagecal.sh"
#  - docker exec --env BRANCH=$BRANCH arch-build /bin/bash -c "/travis/workdir/build-tests/arch/prepare-arch.sh"
#  - docker exec --env BRANCH=$BRANCH arch-build /bin/bash -c "/travis/workdir/build-tests/arch/compile-arch.sh"
